version: "3"

services:
  nodejs:
    image: node:latest
    restart: always
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - "3456:3456"
    command: "npm install && npm run app"
